security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: true
        main:
            anonymous: false
            lazy: true
            guard:
                authenticators:
                    - App\Security\LoginAuthenticator
            json_login:
                check_path: /login
            logout:
                path: logout
                target: logouted
    role_hierarchy:
        # USER
        ROLE_USER_READ: ROLE_USER
        ROLE_USER_WRITE: ROLE_USER_READ
        ROLE_USER_ADMIN: ROLE_USER_WRITE