security:
    encoders:
        App\Entity\User:
            algorithm: auto

    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: true
        main:
            anonymous: false
            lazy: true
            json_login:
                check_path: /login
            logout:
                path: api_logout
                target: logouted

    access_control:
        - { path: '/check', roles: [ROLE_ADMIN, IS_AUTHENTICATED_FULLY] }
