version: '3.7'
services:
  db:
    build: .docker/mysql
    container_name: 'apidb'
    restart: 'always'
    ports:
      - "3350:3306"
    volumes:
      - $DB_VOLUME:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
  php:
    build:
      context: .docker/php-fpm
      args:
        TIMEZONE: $TIMEZONE
    container_name: apiphp
    volumes:
      - ../api:$PROJECT_DIR:cached
      - .docker/logs/symfony:$PROJECT_DIR/var/log:cached
    links:
      - db
  nginx:
    build: .docker/nginx
    container_name: apinginx
    ports:
      - 8051:80
    links:
      - php
    volumes:
      - .docker/logs/nginx:/var/log/nginx:cached
      - ../api:$PROJECT_DIR:cached
