doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver: 'pdo_mysql'
        server_version: '5.7'
        user: 'root'
        password: 'docker'
        host: 'mysql'
        dbname: 'apidb_test'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    auto_mapping: true
    mappings:
      App:
        is_bundle: false
        type: annotation
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
